server:
  port: 8765
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: eureka-hi2
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411/
