server:
  port: 8764
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: eureka-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: eureka-feign
        uri: lb://eureka-feign
        predicates:
        - Path=/demo/**
        # 添加断路器
        filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback
logging:
  level:
    org.springframework.cloud.gateway: debug
hystrix:
  command:
    fallbackcmd:
      timeout:
        enabled: true
      execution:
        thread:
          timeoutInMilliseconds: 15000

